### ISSUE TITLE
Cannot display map

### ISSUE THREAD

**Issue by baggio1117** [googlemaps-samples/android-navigation-samples#1]
I used the same map_api_key, which showed the map in [android-samples](https://github.com/googlemaps-samples/android-samples), but not in [android-navigation-samples](https://github.com/googlemaps-samples/android-navigation-samples)

**Comment by kshirsagarps** [comment]
Currently, the Navigation SDK is only available to a select group of customers. To learn more about getting access to the SDK, [contact the sales team](https://cloud.google.com/contact-maps). Once you have access, you will be able to enable the Navigation SDK on your API key.
